--[[
-- Add some constants from raylib.h not generated by inclua
--]]
local raylib = require 'c_raylib'

raylib.LIGHTGRAY  = raylib.Color(200, 200, 200, 255)
raylib.GRAY       = raylib.Color(130, 130, 130, 255)
raylib.DARKGRAY   = raylib.Color(80, 80, 80, 255)
raylib.YELLOW     = raylib.Color(253, 249, 0, 255)
raylib.GOLD       = raylib.Color(255, 203, 0, 255)
raylib.ORANGE     = raylib.Color(255, 161, 0, 255)
raylib.PINK       = raylib.Color(255, 109, 194, 255)
raylib.RED        = raylib.Color(230, 41, 55, 255)
raylib.MAROON     = raylib.Color(190, 33, 55, 255)
raylib.GREEN      = raylib.Color(0, 228, 48, 255)
raylib.LIME       = raylib.Color(0, 158, 47, 255)
raylib.DARKGREEN  = raylib.Color(0, 117, 44, 255)
raylib.SKYBLUE    = raylib.Color(102, 191, 255, 255)
raylib.BLUE       = raylib.Color(0, 121, 241, 255)
raylib.DARKBLUE   = raylib.Color(0, 82, 172, 255)
raylib.PURPLE     = raylib.Color(200, 122, 255, 255)
raylib.VIOLET     = raylib.Color(135, 60, 190, 255)
raylib.DARKPURPLE = raylib.Color(112, 31, 126, 255)
raylib.BEIGE      = raylib.Color(211, 176, 131, 255)
raylib.BROWN      = raylib.Color(127, 106, 79, 255)
raylib.DARKBROWN  = raylib.Color(76, 63, 47, 255)

raylib.WHITE      = raylib.Color(255, 255, 255, 255)
raylib.BLACK      = raylib.Color(0, 0, 0, 255)
raylib.BLANK      = raylib.Color(0, 0, 0, 0)
raylib.MAGENTA    = raylib.Color(255, 0, 255, 255)
raylib.RAYWHITE   = raylib.Color(245, 245, 245, 255)

return raylib
