__version__ = '0.2.0'
__all__ = ['annotations', 'error', 'namespace']

notice_lines = [
    "This file was automatically generated by Inclua " + __version__ + " (https://github.com/gilzoide/inclua)",
    "",
    "The Inclua team hopes this file was accurately generated, that it will be useful",
    "and will never give SEGFAULTs, throw exceptions, or panic in a similar way.",
    "This software is provided 'as-is', without any warranty.",
    "Feel free to change and redistribute it.",
]
