## Copyright 2016 Gil Barbosa Reis <gilzoide@gmail.com>
# This file is part of Inclua.
#
# Inclua is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# Inclua is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with Inclua.  If not, see <http://www.gnu.org/licenses/>.

"""General infomation about Inclua, like version and so. A common notice for
generated wrappers is also available, possibly commented like C."""

import re

version = '0.1.3'

# Generated wrappers notice, provided as a list so that any generator functions
# can use it not only in C, but whatever suits it better (use str.join or
# whatever)
notice = [
    "This file was automatically generated by Inclua " + version,
    "",
    "The Inclua team hopes this file was accurately generated,",
    "that it will be useful and will never give a SEGFAULT.",
    "This file is distributed without any warranty.",
    "Fell free to change and distribute it, just be careful.",
]


# Notice written as a C/C++ comment
C_notice = r"""/* {}
 */""".format ('\n * '.join (notice))

